name: Build Lua

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.1", "5.1.4"]
        machineTag: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.machineTag }}

    steps:
    - uses: actions/checkout@main

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build Lua
      uses: './'
      with:
        luaVersion: ${{ matrix.luaVersion }}
        buildCache: true

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lua-${{ matrix.luaVersion }}
        path: './'

    - name: Test Lua
      run: lua -e "print('hi from lua')"

  test-cache:
    needs: build

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.1", "5.1.4"]
        machineTag: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.machineTag }}

    steps:
    - uses: actions/checkout@main

    - name: Get Lua from cache
      uses: './'
      with:
        luaVersion: ${{ matrix.luaVersion }}
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lua-${{ matrix.luaVersion }}
        path: './'

    - name: Test Lua
      run: lua -e "print('hi from lua')"
