name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.1", "5.1.4", "5.3", "5.4"]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    name: split test (using lua ${{ matrix.luaVersion }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: actions/upload-artifact@v3
      with:
          name: ${{ matrix.luaVersion }}-${{ matrix.os }}-build
          path: './'
